### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by LovelyHaochi** [hczhcz/telegram-kuso-bots#3]
如果我需要自己部署一个小游戏Bot
`const config = require('./config');`
config里面是什么呢？

**Comment by hczhcz** [comment]
`module.exports = {...}`

object里面的字段自行填写

**Comment by LovelyHaochi** [comment]
> `module.exports = {...}`
> 
> object里面的字段自行填写

谢谢！

**Comment by LovelyHaochi** [comment]
> `module.exports = {...}`
> 
> object里面的字段自行填写

再请教个问题，[minesweeper.js](https://github.com/hczhcz/telegram-kuso-bots/blob/master/minesweeper.js) 的第6行
```const bot = require('./bot.' + config.bot)(config.minesweeperToken);```
这里的 `require('./bot.' + config.bot)` 是???

**Comment by hczhcz** [comment]
`'tg'`或者`'tgf'`，后者用tgfancy框架

**Comment by LovelyHaochi** [comment]
> `'tg'`或者`'tgf'`，后者用tgfancy框架

我使用了tgfancy框架，但他报错
```
-bash-4.2# node minesweeper.js
module.js:478
    throw err;
    ^

Error: Cannot find module './bot.tgf'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/mine/minesweeper.js:6:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```
请问我具体/大概应该怎么操作？

**Comment by LovelyHaochi** [comment]
我在你仓库里找到了 😆 谢谢大佬帮助
